#### 1. Librerías.

In [1]:
%run "./librerias/librerias.ipynb"

#### 2. Constantes.

In [2]:
#a. Modo de ejecución (se define en ./constantes/modo.txt, un solo lugar para los 4 notebooks).
# "validacion" = entreno solo con train, puedo medir nDCG.
# "entrega"    = entreno con train+test, uso todo el historial para predecir.
with open("./constantes/modo.txt") as f:
    MODO = f.read().strip()

assert MODO in ("validacion", "entrega"), f"MODO inválido: {MODO!r}"
print(f"MODO: {MODO}")

MODO: validacion

In [3]:
#b. Otras constantes.
%run "./constantes/constantes.ipynb"

In [4]:
#c. Verificación del modo (que los paths coincidan con lo que creo que estoy corriendo).
print(f"MODO: {MODO} | sufijo: {sufijo!r}")
print(f"train_fe: {path_train_fe}")
print(f"modelo:   {path_modelo}")

MODO: validacion | sufijo: ''
train_fe: ./inputs/train_fe.csv
modelo:   ./modelos/modelo.pkl

#### 3. Funciones.

In [5]:
%run "./funciones/funciones.ipynb"

#### 4. Lecturas.

In [6]:
#a. Train.
df_train = pd.read_csv(path_train_fe)

In [7]:
#b. Test (solo hace falta para evaluar; en entrega ya está dentro de la base).
if MODO == "validacion":
    df_test = pd.read_csv(path_test_crudo, dtype={"id_lector": str, "id_libro": str})

In [8]:
#c. Dataset a predecir.
df_a_predecir = pd.read_csv(path_a_predecir)

In [9]:
#d. Libros y Lectores (lo tomo para armar df_test).
df_libros = pd.read_csv(path_libros_fe)
df_lectores = pd.read_csv(path_lectores_fe)

#### 5. Preparación previa.

In [10]:
#a. Forma final.
print(f"Train: {df_train.shape}")
print("\n")

Train: (383547, 122)

In [11]:
#b. Me aseguro que no hayan quedado nulos en los ratings.
cols_rating = [c for c in df_train.columns if c.startswith("rating_prom")]
print("Train.")
print(df_train[cols_rating].isna().sum())

Train.
rating_prom_id_lector                          0
rating_prom_id_lector_autor                    0
rating_prom_id_lector_genero_libro_agrupado    0
rating_prom_id_libro                           0
rating_prom_autor                              0
rating_prom_genero                             0
dtype: int64

In [12]:
#c. Armo X e y. 
features_base = [
    "anio_edicion", 
    "nacimiento",
    #"edad_al_interactuar", 
    #"dias_transcurridos_interaccion", # Es 0 en test/producción siempre.
    #"anios_transcurridos_edicion",
    #"antiguedad_libro_hoy", # Es igual a anios_transcurridos_edicion en test/producción.
    'frecuencia_lector', 
    'frecuencia_libro', 
    'n_interacciones_lector_autor',
    'n_interacciones_lector_genero', 
    'n_lectores_distintos_autor',
    #'rating_prom_id_lector', 
    'rating_prom_id_lector_autor',
    'rating_prom_id_lector_genero_libro_agrupado', 
    #'rating_prom_id_libro', # Con RF sobre RMSE, las features de calidad de ítem degradan el ranking porque desplazan a las de afinidad. Usar con un algoritmo que ordene, no que sea pointwise. 
    #'rating_prom_autor',    # Con RF sobre RMSE, las features de calidad de ítem degradan el ranking porque desplazan a las de afinidad. Usar con un algoritmo que ordene, no que sea pointwise. 
    #'rating_prom_genero',   # Con RF sobre RMSE, las features de calidad de ítem degradan el ranking porque desplazan a las de afinidad. Usar con un algoritmo que ordene, no que sea pointwise. 
    'n_autores_distintos_lector',
    'n_generos_distintos_lector'
]
features_dummies = [c for c in df_train.columns if c.startswith((
    "genero_persona_", 
    #"genero_libro_agrupado_", 
    #"editorial_agrupada_", 
    #"pais_agrupado_"
))]
features = features_base + features_dummies

X = df_train[features]
y = df_train["rating"]

In [13]:
#d. Entreno con todas las filas en ambos modos: el nDCG no usa el holdout interno
# (se calcula sobre df_test con el loop de retrieval), así que separar un 20%
# solo sirve para el RMSE y hace que el modelo que valido no sea el que entrego.
X_train, y_train = X, y
print(f"Modo {MODO}: entreno con las {len(X)} filas.")

Modo validacion: entreno con las 383547 filas.

#### 6. Entrenamiento.

In [ ]:
#a. Busco hiperparametros con RandomizedSearchCV.
#i. Espacio de búsqueda.
#param_dist = {
#    "n_estimators": [100, 200, 500],
#    "max_depth": [10, 20, 30],
#    "min_samples_leaf": [3, 5, 10],
#    "min_samples_split": [5, 10],
#    "max_features": ["sqrt", "log2"],
#}

#ii. Armo la búsqueda.
#busqueda = RandomizedSearchCV(
#    estimator=RandomForestRegressor(random_state=42, n_jobs=1),
#    param_distributions=param_dist,
#    n_iter=30,
#    scoring="neg_root_mean_squared_error",
#    cv=3,
#    random_state=42,
#    verbose=2,
#    n_jobs=-1,
#)

#iii. Corro la búsqueda sobre train.
#busqueda.fit(X_train, y_train)

#iv. Reviso los mejores hiperparámetros encontrados.
#print("Mejores hiperparámetros:", busqueda.best_params_)
#print("Mejor RMSE (CV, promedio de los 3 folds):", -busqueda.best_score_)

# Si quiero dejar congelado los hiperparámetros.
rf = RandomForestRegressor(
    n_estimators=500,
    max_depth=30,
    min_samples_leaf=3,
    min_samples_split=10,
    max_features="sqrt",
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train,y_train)

RandomForestRegressor(max_depth=30, max_features='sqrt', min_samples_leaf=3,
                      min_samples_split=10, n_estimators=500, n_jobs=-1,
                      random_state=42)

In [ ]:
#b. Exportamos el modelo entrenado.
joblib.dump(rf, path_modelo)
print(f"Modelo exportado con exito en: {path_modelo}")

Modelo exportado con exito en: ./modelos/modelo.pkl

In [ ]:
#c. En modo entrega el notebook termina aca: lo que sigue es evaluacion,
# y no tiene sentido evaluar contra un test que ya esta dentro del entrenamiento.
if MODO != "validacion":
    print("\nModo entrega: fin del notebook 3. Segui con el notebook 4.")
    raise KeyboardInterrupt("Corte intencional: modo entrega.")

#### 7. Evaluación del modelo sobre test -  nDCG@20.

In [14]:
#a. Precómputos (fuera del loop).
#1. Universo de libros.
conn = sqlite3.connect(path_db)
todos_los_libros = pd.read_sql("SELECT id_libro FROM interacciones", conn)["id_libro"].unique()
conn.close()
#2. Historial por lector.
leidos_por_lector = df_train[["id_lector","id_libro"]].groupby("id_lector")["id_libro"].apply(set).to_dict()
#3. Ground truth por lector.
gt_por_lector = {lid: pd.Series(g["rating"].values, index=g["id_libro"].values)
                 for lid, g in df_test.groupby("id_lector")}
#4. Lectores de test a recomendarle.
id_lectores_test = df_test["id_lector"].unique()

In [15]:
df_libros[(df_libros["id_libro"].isin(todos_los_libros))&(df_libros["isbn"].isna())]

,id_libro,titulo,autor,genero_libro,editorial,anio_edicion,isbn,resumen,img_src,genero_libro_agrupado,editorial_agrupada
40750,quienes-somos,NaN,NaN,NaN,NaN,2011,NaN,NaN,NaN,sin_dato,otras

In [16]:
print(len(set(todos_los_libros) - set(df_libros["id_libro"])))

70

,id_libro,titulo,autor,genero_libro,editorial,anio_edicion,isbn,resumen,img_src,genero_libro_agrupado,editorial_agrupada
40750,quienes-somos,NaN,NaN,NaN,NaN,2011,NaN,NaN,NaN,sin_dato,otras

In [18]:
#b. Tablas de referencia para el feature engineering de los candidatos.
#i. Armo las tablas.
(media_global, caract_lector, caract_libros,
 afinidad_lector_autor_test, afinidad_lector_genero_test) = armar_tablas_referencia(
    df_train, df_libros, df_lectores
)

Nulos caract_lector: ninguno
Nulos caract_libros: {'autor': 78227, 'genero_libro_agrupado': 78220}
Duplicados (lector / libro / lector-autor / lector-genero): 0 0 0 0
Lectores: 11285 | Libros: 128743 | Libros sin interacciones en la base: 84772

In [ ]:
#ii. Comprobación.
print(
    "Duplicados lectores:",
    caract_lector["id_lector"].duplicated().sum()
)

print(
    "Duplicados libros:",
    caract_libros["id_libro"].zduplicated().sum()
)

print(
    "Duplicados lector-autor:",
    afinidad_lector_autor_test
    .duplicated(["id_lector", "autor"])
    .sum()
)

print(
    "Duplicados lector-género:",
    afinidad_lector_genero_test
    .duplicated(["id_lector", "genero_libro_agrupado"])
    .sum()
)

Duplicados lectores: 0
Duplicados libros: 0
Duplicados lector-autor: 0
Duplicados lector-género: 0

In [ ]:
#c. Genero una muestra de test (para no correrlo todos).
#lectores_test_muestra = (z
#    df_test["id_lector"]
#    .drop_duplicates()
#    .sample(
#        n=1000,
#        random_state=42
#    )
#    .tolist()
#)

#c. Genero una muestra de test estratificada por frecuencia, para que la composición
# se parezca a la de los lectores que evalúa Kaggle (mediana ~103, la mía era ~45).
# Sin esto optimizo para lectores livianos y me miden sobre pesados.
freq_train = df_train.groupby("id_lector").size()
bins = [-1, 0, 20, 50, 100, 250, np.inf]

#i. Distribución objetivo: la de los lectores a predecir.
freq_objetivo = df_a_predecir["id_lector"].map(freq_train).fillna(0)
pesos_objetivo = pd.cut(freq_objetivo, bins).value_counts(normalize=True)

#ii. Lectores disponibles en test, con su bucket.
disponibles = pd.DataFrame({"id_lector": df_test["id_lector"].drop_duplicates().sort_values()})
disponibles["freq"] = disponibles["id_lector"].map(freq_train).fillna(0)
disponibles["bucket"] = pd.cut(disponibles["freq"], bins)

#iii. Muestreo cada bucket según el peso objetivo (o todo lo que haya, si no alcanza).
n_total = 1000
partes = []
for bucket, peso in pesos_objetivo.items():
    pool = disponibles[disponibles["bucket"] == bucket]
    n_pedido = int(round(peso * n_total))
    partes.append(pool.sample(n=min(n_pedido, len(pool)), random_state=42))

muestra = pd.concat(partes)
lectores_test_muestra = muestra["id_lector"].tolist()

#iv. Comprobación.
print(f"Muestra: {len(lectores_test_muestra)} lectores")
print(pd.DataFrame({
    "objetivo": pesos_objetivo,
    "muestra": muestra["bucket"].value_counts(normalize=True)
}).round(3))

Muestra: 1001 lectores
                objetivo  muestra
(0.0, 20.0]        0.281    0.281
(100.0, 250.0]     0.236    0.236
(250.0, inf]       0.173    0.173
(50.0, 100.0]      0.159    0.159
(20.0, 50.0]       0.129    0.129
(-1.0, 0.0]        0.023    0.023

In [21]:
#d. Calculamos.
#i. Lista vacía donde iré almacenando los nDCG de cada usuario, y datos para luego monitorear.
ndcg_lista = []
total_lectores = len(lectores_test_muestra)
print("Comienza la predicción general.")
#ii. Recorro cada id_lector a recomendar.
for i, id_lector in enumerate(lectores_test_muestra, start=1):
    print("\nLector: {} {}/{}".format(id_lector, i, total_lectores))
    #1. Me traigo los libros a recomendarle al id_lector.
    #print("1. Retrieval.")
    libros_candidatos_a_recomendar = retrieval(id_lector)

    #2. Me traigo el Ground Truth del lector (que por diseño, son 20 en test).
    #print("2. Me traigo el True Relevance.")
    true_relevance = gt_por_lector[id_lector]

    #3. Realizo el feature engineering sobre todos los libros candidatos a recomendar.
    #print("3. Armo las features de los libros candidatos.")
    df_features_candidatos = feature_engineering_test(id_lector, libros_candidatos_a_recomendar)

    #4. Predigo el ranking para cada libro candidato del id_lector
    #print("4. Predigo sobre los libros candidatos su rating.")
    predicted_scores_dict = ranking(df_features_candidatos, features, rf)

    #5. Creo una lista de los libros verdaderos + los que evalué, universo en común a evaluar.
    id_libros = list(set(true_relevance.index) |set(predicted_scores_dict.keys()))

    #6. Traigo el rating real de cada libro. Si no es relevante, entonces = 0.
    y_true = np.asarray([[true_relevance.get(id_libro, 0) for id_libro in id_libros]])

    #7. Traigo el rating predicho por el modelo de cada libro. Si no lo evaluó, entonces = 0.
    y_score = np.asarray([[predicted_scores_dict.get(id_libro, 0) for id_libro in id_libros]])

    #8. Calculo el nDCG@20 para el id_lector.
    #print("5. Calculo el nDCG para el lector en cuestión.")
    ndcg = ndcg_score(y_true, y_score, k=20)

    #9. Lo agrego a la lista.
    ndcg_lista.append(ndcg)

    #10. Imprimo el nDCG del id_lector.
    print("El nCDG es de:{}".format(ndcg))
    
#iii. Imprimo el nDCG promedio de todos los id_lectores a predecir.
ndcg_arr = np.array(ndcg_lista)
print("\nEl nDCG@20 promedio es: {:.4f} ± {:.4f} (SE)".format(ndcg_arr.mean(), ndcg_arr.std(ddof=1) / np.sqrt(len(ndcg_arr))))

Comienza la predicción general.

Lector: msor 1/1001
El nCDG es de:0.0

Lector: pmarre 2/1001
El nCDG es de:0.22892428671909032

Lector: galu 3/1001
El nCDG es de:0.0

Lector: ishmael 4/1001
El nCDG es de:0.16832638224488078

Lector: mibagoz 5/1001
El nCDG es de:0.0

Lector: andrestorres 6/1001
El nCDG es de:0.14613388727877552

Lector: jose-m-santos 7/1001
El nCDG es de:0.0

Lector: albertocm 8/1001
El nCDG es de:0.0

Lector: sony69 9/1001
El nCDG es de:0.039454432976902085

Lector: rubio-rose 10/1001
El nCDG es de:0.0

Lector: misaeltv1 11/1001
El nCDG es de:0.20701303746650898

Lector: amaiauc 12/1001
El nCDG es de:0.13019370594783017

Lector: lisa210 13/1001
El nCDG es de:0.0

Lector: mmj 14/1001
El nCDG es de:0.09555514044680816

Lector: mihernan 15/1001
El nCDG es de:0.22242261183009296

Lector: qqq25 16/1001
El nCDG es de:0.0

Lector: martinalvarezalcaire 17/1001
El nCDG es de:0.24310415958872386

Lector: niobe29 18/1001
El nCDG es de:0.3126753014978023

Lector: merchesotodeltoro 19/1001
El nCDG es de:0.23165732683700074

Lector: giovanniro255 20/1001
El nCDG es de:0.201707242331655

Lector: anate 21/1001
El nCDG es de:0.048500835083086516

Lector: dbuenosal 22/1001
El nCDG es de:0.31115928241362

Lector: rubin 23/1001
El nCDG es de:0.02706698417978998

Lector: ayda 24/1001
El nCDG es de:0.0

Lector: azcu 25/1001
El nCDG es de:0.033912929816184684

Lector: ainhoa 26/1001
El nCDG es de:0.09820194624610622

Lector: cristinapantis 27/1001
El nCDG es de:0.2418446625243866

Lector: db-pacman 28/1001
El nCDG es de:0.0

Lector: dani-els 29/1001
El nCDG es de:0.0

Lector: analeo11 30/1001
El nCDG es de:0.0

Lector: angel8 31/1001
El nCDG es de:0.3128515653809335

Lector: hugolatra 32/1001
El nCDG es de:0.3457884752206126

Lector: patba 33/1001
El nCDG es de:0.16796500660953312

Lector: joshman5on 34/1001
El nCDG es de:0.22783699234570118

Lector: radamantis 35/1001
El nCDG es de:0.03474258766738806

Lector: 2046841688723116 36/1001
El nCDG es de:0.0

Lector: sahara 37/1001
El nCDG es de:0.033351561266461875

Lector: toniflap 38/1001
El nCDG es de:0.0

Lector: inma 39/1001
El nCDG es de:0.0

Lector: linange742 40/1001
El nCDG es de:0.0

Lector: dani-romeo 41/1001
El nCDG es de:0.0

Lector: fmiguelez 42/1001
El nCDG es de:0.02534768153209916

Lector: pereticoreberteno 43/1001
El nCDG es de:0.0

Lector: brenda-ruote 44/1001
El nCDG es de:0.0

Lector: paolaconlibros 45/1001
El nCDG es de:0.0

Lector: yolldragon 46/1001
El nCDG es de:0.0

Lector: amg11 47/1001
El nCDG es de:0.3510413224293901

Lector: julio-enrique-94849 48/1001
El nCDG es de:0.0

Lector: tegon 49/1001
El nCDG es de:0.040835121722385154

Lector: mat-as-lagos-castro 50/1001
El nCDG es de:0.0

Lector: enriqueramlo 51/1001
El nCDG es de:0.0

Lector: jerovaz 52/1001
El nCDG es de:0.030107273438429918

Lector: cannier 53/1001
El nCDG es de:0.2160138646853441

Lector: escribano 54/1001
El nCDG es de:0.12709965453658845

Lector: nataliarodriguez 55/1001
El nCDG es de:0.0

Lector: alexfa1893 56/1001
El nCDG es de:0.2496005105969569

Lector: sebasmurgas 57/1001
El nCDG es de:0.12171558732518264

Lector: ubeket 58/1001
El nCDG es de:0.0

Lector: carlas 59/1001
El nCDG es de:0.5063680532366159

Lector: juandfm 60/1001
El nCDG es de:0.0

Lector: paola02 61/1001
El nCDG es de:0.5470070480860553

Lector: strongman2 62/1001
El nCDG es de:0.02865010584422447

Lector: akusmeren 63/1001
El nCDG es de:0.1828065671980706

Lector: gonjordan 64/1001
El nCDG es de:0.34247953149256943

Lector: zaaanon 65/1001
El nCDG es de:0.0

Lector: sheena-kraus 66/1001
El nCDG es de:0.0

Lector: duyunsheng 67/1001
El nCDG es de:0.22705663197558745

Lector: kaizen79 68/1001
El nCDG es de:0.0

Lector: huck 69/1001
El nCDG es de:0.1420400396336573

Lector: lauragomezve 70/1001
El nCDG es de:0.20758162946641354

Lector: josefa-martinez-saez 71/1001
El nCDG es de:0.0

Lector: ela 72/1001
El nCDG es de:0.0

Lector: duardo1999 73/1001
El nCDG es de:0.0

Lector: fonso10t 74/1001
El nCDG es de:0.11223310141061561

Lector: lolitas2 75/1001
El nCDG es de:0.0

Lector: elphaba 76/1001
El nCDG es de:0.35276643680657255

Lector: coldplayer13 77/1001
El nCDG es de:0.0845509514718583

Lector: margarey 78/1001
El nCDG es de:0.0

Lector: theonor 79/1001
El nCDG es de:0.0

Lector: antoniorcano 80/1001
El nCDG es de:0.06075108448732838

Lector: depcmathotmailcom 81/1001
El nCDG es de:0.22952286153780452

Lector: ac12 82/1001
El nCDG es de:0.09282006090636175

Lector: chechus 83/1001
El nCDG es de:0.5315046840232539

Lector: unmontoto 84/1001
El nCDG es de:0.18019293717861976

Lector: mariaeugenia 85/1001
El nCDG es de:0.05865718769477515

Lector: r-299-d-257 86/1001
El nCDG es de:0.1966248363663254

Lector: mcaroperezp 87/1001
El nCDG es de:0.1480280285902114

Lector: carolyafri 88/1001
El nCDG es de:0.0

Lector: blumm 89/1001
El nCDG es de:0.0

Lector: der-halbgott 90/1001
El nCDG es de:0.1167791880901104

Lector: elflautista 91/1001
El nCDG es de:0.07490979928219618

Lector: mlabaca 92/1001
El nCDG es de:0.47442411647947447

Lector: elenafuriaste 93/1001
El nCDG es de:0.0

Lector: armandilio 94/1001
El nCDG es de:0.0

Lector: julietatata 95/1001
El nCDG es de:0.20739331009285739

Lector: faxed 96/1001
El nCDG es de:0.0

Lector: crispin2 97/1001
El nCDG es de:0.0

Lector: elendil 98/1001
El nCDG es de:0.1592998759955807

Lector: sawyer 99/1001
El nCDG es de:0.0962957540104929

Lector: estano 100/1001
El nCDG es de:0.0

Lector: mariapmujica 101/1001
El nCDG es de:0.39736280202108226

Lector: 10213785336057608 102/1001
El nCDG es de:0.10163435555923651

Lector: euggy 103/1001
El nCDG es de:0.13522278504599466

Lector: endiabladamente 104/1001
El nCDG es de:0.0

Lector: mariamiri 105/1001
El nCDG es de:0.08759504487718862

Lector: carl992 106/1001
El nCDG es de:0.282668241389748

Lector: jaimitzu 107/1001
El nCDG es de:0.12262871133427869

Lector: luriki_sus 108/1001
El nCDG es de:0.3289393603375843

Lector: notiku 109/1001
El nCDG es de:0.15952217567643043

Lector: et888 110/1001
El nCDG es de:0.0

Lector: souadaccesorios 111/1001
El nCDG es de:0.0

Lector: kary-caraza 112/1001
El nCDG es de:0.150647728387245

Lector: manuel-diaz-73113 113/1001
El nCDG es de:0.255930580917

Lector: silvia-laherran 114/1001
El nCDG es de:0.15281318766604546

Lector: marcelotapiabau 115/1001
El nCDG es de:0.0

Lector: mia_22 116/1001
El nCDG es de:0.0

Lector: nanilibros 117/1001
El nCDG es de:0.0

Lector: miriammonre 118/1001
El nCDG es de:0.19083655813170475

Lector: ajmangas 119/1001
El nCDG es de:0.0

Lector: andres-cervantes 120/1001
El nCDG es de:0.3249416583561635

Lector: albivioleta 121/1001
El nCDG es de:0.0

Lector: caroline-moran 122/1001
El nCDG es de:0.30383126895174545

Lector: mile-gauna-9 123/1001
El nCDG es de:0.0

Lector: nachoal 124/1001
El nCDG es de:0.24480235795415262

Lector: maca-olate 125/1001
El nCDG es de:0.04113606392530275

Lector: delirio_peto 126/1001
El nCDG es de:0.3976645205105472

Lector: glous09 127/1001
El nCDG es de:0.041571914184320054

Lector: tinton 128/1001
El nCDG es de:0.21765180339367193

Lector: princesaleia 129/1001
El nCDG es de:0.26770421363569535

Lector: juliomoreno 130/1001
El nCDG es de:0.0

Lector: fernilo 131/1001
El nCDG es de:0.048853960625360814

Lector: jribas 132/1001
El nCDG es de:0.0

Lector: caro 133/1001
El nCDG es de:0.1185843208537725

Lector: pablogari 134/1001
El nCDG es de:0.311570508603558

Lector: gabrielo 135/1001
El nCDG es de:0.07111772112523924

Lector: alvaro_mase 136/1001
El nCDG es de:0.25479122852227215

Lector: jandrojamon 137/1001
El nCDG es de:0.039557087987938916

Lector: helen-eliana 138/1001
El nCDG es de:0.14273396982732753

Lector: raudix 139/1001
El nCDG es de:0.0

Lector: gabira14 140/1001
El nCDG es de:0.0

Lector: denislovage 141/1001
El nCDG es de:0.16041496410886344

Lector: joan-gotham 142/1001
El nCDG es de:0.0

Lector: liena 143/1001
El nCDG es de:0.0

Lector: giat-coffee 144/1001
El nCDG es de:0.0

Lector: almale 145/1001
El nCDG es de:0.30510708650313806

Lector: serjob 146/1001
El nCDG es de:0.05111900207846834

Lector: arishi0 147/1001
El nCDG es de:0.0

Lector: chuetas 148/1001
El nCDG es de:0.04166230087607675

Lector: laura2210 149/1001
El nCDG es de:0.03814933087287886

Lector: conchita 150/1001
El nCDG es de:0.0

Lector: dovas 151/1001
El nCDG es de:0.1527639415538522

Lector: armantleyotl 152/1001
El nCDG es de:0.0

Lector: ibarak 153/1001
El nCDG es de:0.15844552698180964

Lector: delico 154/1001
El nCDG es de:0.2881844980884141

Lector: najho14 155/1001
El nCDG es de:0.0466304959969504

Lector: arkantos 156/1001
El nCDG es de:0.0

Lector: solde 157/1001
El nCDG es de:0.0

Lector: jana-aug-rog 158/1001
El nCDG es de:0.22307965566164303

Lector: kvothe7 159/1001
El nCDG es de:0.4768356815899328

Lector: rb 160/1001
El nCDG es de:0.0

Lector: munchi 161/1001
El nCDG es de:0.0

Lector: gora_gu 162/1001
El nCDG es de:0.0

Lector: juanmanueldiez 163/1001
El nCDG es de:0.0

Lector: deivid13lj 164/1001
El nCDG es de:0.3725832993624531

Lector: jessica-perez-roman 165/1001
El nCDG es de:0.04530326105385563

Lector: xuxus16 166/1001
El nCDG es de:0.08862704613222837

Lector: jose-luis-conde-huelga 167/1001
El nCDG es de:0.04747381706470949

Lector: lauragtf01 168/1001
El nCDG es de:0.0

Lector: pablo-pastore 169/1001
El nCDG es de:0.0

Lector: trotalibros 170/1001
El nCDG es de:0.0

Lector: pepinha 171/1001
El nCDG es de:0.07314298073714647

Lector: esteparia 172/1001
El nCDG es de:0.32111350944395645

Lector: juan-iradier 173/1001
El nCDG es de:0.11641085056776054

Lector: almarel 174/1001
El nCDG es de:0.0

Lector: cold-days 175/1001
El nCDG es de:0.5117685199420433

Lector: vicki 176/1001
El nCDG es de:0.18796401127904838

Lector: rgpegue 177/1001
El nCDG es de:0.0

Lector: rekete-meli 178/1001
El nCDG es de:0.0

Lector: hungerreader 179/1001
El nCDG es de:0.1714538488649486

Lector: mealvarenga 180/1001
El nCDG es de:0.08346458771203907

Lector: adrism28d 181/1001
El nCDG es de:0.0

Lector: abril2004 182/1001
El nCDG es de:0.03853739958038164

Lector: pablorogala 183/1001
El nCDG es de:0.05007868677950755

Lector: ariel 184/1001
El nCDG es de:0.0

Lector: alba-casas 185/1001
El nCDG es de:0.17002831283513967

Lector: pabloep 186/1001
El nCDG es de:0.2534869517494279

Lector: disdis 187/1001
El nCDG es de:0.0

Lector: john-bonilla 188/1001
El nCDG es de:0.0

Lector: laequilibrista 189/1001
El nCDG es de:0.0

Lector: emiri 190/1001
El nCDG es de:0.06239058089932055

Lector: pilarmy 191/1001
El nCDG es de:0.0

Lector: 10155083334237680 192/1001
El nCDG es de:0.14267362607157058

Lector: mayramn44 193/1001
El nCDG es de:0.04013016787628413

Lector: joshborras 194/1001
El nCDG es de:0.0

Lector: weekend 195/1001
El nCDG es de:0.0

Lector: nomepises-quellevochanclas 196/1001
El nCDG es de:0.0

Lector: monica-cueva 197/1001
El nCDG es de:0.19705641318960876

Lector: nico11 198/1001
El nCDG es de:0.07147763460750542

Lector: dick-94 199/1001
El nCDG es de:0.05871797411412513

Lector: princesabego 200/1001
El nCDG es de:0.0570087654674337

Lector: josegolem 201/1001
El nCDG es de:0.11383344565671805

Lector: albertrg95 202/1001
El nCDG es de:0.12315151232642683

Lector: marealiteraria 203/1001
El nCDG es de:0.0

Lector: luciap 204/1001
El nCDG es de:0.044229779431229806

Lector: ale1892 205/1001
El nCDG es de:0.6007655058676429

Lector: dana 206/1001
El nCDG es de:0.026074663705117646

Lector: youngwise 207/1001
El nCDG es de:0.2219023394343581

Lector: lozano-wendy 208/1001
El nCDG es de:0.0

Lector: anasua 209/1001
El nCDG es de:0.0

Lector: belladona 210/1001
El nCDG es de:0.0

Lector: kaliam 211/1001
El nCDG es de:0.03323213945548143

Lector: fedec 212/1001
El nCDG es de:0.0

Lector: cynthia-lugo 213/1001
El nCDG es de:0.13568472436542095

Lector: ts89 214/1001
El nCDG es de:0.0

Lector: irisolda 215/1001
El nCDG es de:0.2075979005839727

Lector: cesla 216/1001
El nCDG es de:0.0

Lector: fabia 217/1001
El nCDG es de:0.03626972531680559

Lector: noeliarp23-1 218/1001
El nCDG es de:0.10511786985773942

Lector: greg 219/1001
El nCDG es de:0.5949405298474794

Lector: energiecottbus 220/1001
El nCDG es de:0.0

Lector: zearil 221/1001
El nCDG es de:0.0

Lector: yoli82 222/1001
El nCDG es de:0.0

Lector: alejandroparadissandstromatgmailcom 223/1001
El nCDG es de:0.0

Lector: plata33 224/1001
El nCDG es de:0.0

Lector: alessgimenez 225/1001
El nCDG es de:0.0

Lector: jul 226/1001
El nCDG es de:0.0

Lector: guada 227/1001
El nCDG es de:0.13763301615261778

Lector: 10214561384646437 228/1001
El nCDG es de:0.21536414359307035

Lector: fay-anderson1998 229/1001
El nCDG es de:0.0

Lector: mase 230/1001
El nCDG es de:0.1475251793273152

Lector: jfolverag 231/1001
El nCDG es de:0.11994738507037307

Lector: rukimi 232/1001
El nCDG es de:0.06419445012231374

Lector: juana-moraleja 233/1001
El nCDG es de:0.0

Lector: mauricio-mojica-sua 234/1001
El nCDG es de:0.0

Lector: santines 235/1001
El nCDG es de:0.03428754902146775

Lector: mv 236/1001
El nCDG es de:0.0

Lector: cain 237/1001
El nCDG es de:0.14759906800226444

Lector: matias-battistini 238/1001
El nCDG es de:0.2905437144149589

Lector: shuanma 239/1001
El nCDG es de:0.11203142185922602

Lector: paul-w 240/1001
El nCDG es de:0.40357619154566077

Lector: valura 241/1001
El nCDG es de:0.15547839837981703

Lector: majesusm 242/1001
El nCDG es de:0.0

Lector: photomadrid_m 243/1001
El nCDG es de:0.31858075844227135

Lector: ely 244/1001
El nCDG es de:0.0

Lector: trancazo 245/1001
El nCDG es de:0.0

Lector: paula238 246/1001
El nCDG es de:0.07384947465998724

Lector: karmela 247/1001
El nCDG es de:0.0

Lector: nbm 248/1001
El nCDG es de:0.025772597924444786

Lector: mirtenchus 249/1001
El nCDG es de:0.15560767223517205

Lector: marcelo-varela 250/1001
El nCDG es de:0.03635145047783971

Lector: landroval 251/1001
El nCDG es de:0.0

Lector: paulaexodus 252/1001
El nCDG es de:0.054822830131107586

Lector: ciudadanocero 253/1001
El nCDG es de:0.05796506485366523

Lector: gemita 254/1001
El nCDG es de:0.03559228461561893

Lector: masha-pla-5 255/1001
El nCDG es de:0.0

Lector: 10154764701327155 256/1001
El nCDG es de:0.17317281250615935

Lector: 10209011575186208 257/1001
El nCDG es de:0.04468873992714788

Lector: spookywailer 258/1001
El nCDG es de:0.07419775420855139

Lector: rakeldiez 259/1001
El nCDG es de:0.25499224345118005

Lector: ticoba 260/1001
El nCDG es de:0.23143365447142594

Lector: celeste1991 261/1001
El nCDG es de:0.0

Lector: davidalonsofeldhausatgmailcom 262/1001
El nCDG es de:0.0

Lector: ramon-candela 263/1001
El nCDG es de:0.5456265831808843

Lector: nicozalez 264/1001
El nCDG es de:0.22441042896205707

Lector: vismi 265/1001
El nCDG es de:0.242560063234295

Lector: daniel-fregonese 266/1001
El nCDG es de:0.04440748606969756

Lector: whoyouknow 267/1001
El nCDG es de:0.0

Lector: fidel-e-gonzalez 268/1001
El nCDG es de:0.0

Lector: lulu-zanartu 269/1001
El nCDG es de:0.03204059740871024

Lector: glaura 270/1001
El nCDG es de:0.09146323498415468

Lector: reychango 271/1001
El nCDG es de:0.0

Lector: dinise 272/1001
El nCDG es de:0.36385066203186117

Lector: crins 273/1001
El nCDG es de:0.0

Lector: 690663634460200 274/1001
El nCDG es de:0.12516546267323464

Lector: josmig 275/1001
El nCDG es de:0.053666575347788535

Lector: aishamry 276/1001
El nCDG es de:0.0

Lector: andreablez 277/1001
El nCDG es de:0.0

Lector: alberto-moreno-355744 278/1001
El nCDG es de:0.0

Lector: genobyte 279/1001
El nCDG es de:0.41443404170676934

Lector: cazadordelibros 280/1001
El nCDG es de:0.0

Lector: anniemay 281/1001
El nCDG es de:0.0

Lector: mrmely 282/1001
El nCDG es de:0.0

Lector: baltib 283/1001
El nCDG es de:0.0

Lector: ayras 284/1001
El nCDG es de:0.12196945170466544

Lector: franba 285/1001
El nCDG es de:0.0

Lector: juanca_lb 286/1001
El nCDG es de:0.0

Lector: kafkaenlaorilla 287/1001
El nCDG es de:0.0

Lector: heskonerz 288/1001
El nCDG es de:0.0

Lector: julia77 289/1001
El nCDG es de:0.0

Lector: solros 290/1001
El nCDG es de:0.0

Lector: cogumela 291/1001
El nCDG es de:0.0

Lector: didihn81 292/1001
El nCDG es de:0.0

Lector: dr-poirot 293/1001
El nCDG es de:0.0

Lector: luna712 294/1001
El nCDG es de:0.0

Lector: jasperoduss 295/1001
El nCDG es de:0.15322288106824977

Lector: gloria-maria 296/1001
El nCDG es de:0.0

Lector: cmo 297/1001
El nCDG es de:0.13607596414924397

Lector: crismarel 298/1001
El nCDG es de:0.0

Lector: rom 299/1001
El nCDG es de:0.0

Lector: fer_mar 300/1001
El nCDG es de:0.0

Lector: crisbarco 301/1001
El nCDG es de:0.0

Lector: angela-sanchezcastano-3 302/1001
El nCDG es de:0.0

Lector: vickycerro 303/1001
El nCDG es de:0.0

Lector: senalo 304/1001
El nCDG es de:0.0

Lector: lectora62 305/1001
El nCDG es de:0.0

Lector: capitantan 306/1001
El nCDG es de:0.0

Lector: gilito 307/1001
El nCDG es de:0.0402151883039421

Lector: mariano-1 308/1001
El nCDG es de:0.0

Lector: ayrton-slemak 309/1001
El nCDG es de:0.0

Lector: hornosman 310/1001
El nCDG es de:0.11667590572318545

Lector: cecilia-lisbon 311/1001
El nCDG es de:0.0

Lector: antonio-martinmorales-98 312/1001
El nCDG es de:0.0

Lector: maica70 313/1001
El nCDG es de:0.0

Lector: monimage 314/1001
El nCDG es de:0.10024457214550474

Lector: oscar331 315/1001
El nCDG es de:0.0

Lector: sherezade 316/1001
El nCDG es de:0.0

Lector: lebrato 317/1001
El nCDG es de:0.0

Lector: kiliemin 318/1001
El nCDG es de:0.031079045992070953

Lector: evilwonders 319/1001
El nCDG es de:0.02898621794631762

Lector: viedesens 320/1001
El nCDG es de:0.0

Lector: emv 321/1001
El nCDG es de:0.0

Lector: einyelrules 322/1001
El nCDG es de:0.03925803049942821

Lector: rupertouo 323/1001
El nCDG es de:0.0

Lector: nora 324/1001
El nCDG es de:0.07840684946504364

Lector: lidiort 325/1001
El nCDG es de:0.05931744963883883

Lector: esperanza 326/1001
El nCDG es de:0.0

Lector: juan-doblas 327/1001
El nCDG es de:0.1482080160047616

Lector: yolandagata 328/1001
El nCDG es de:0.030937127778664728

Lector: hielo80 329/1001
El nCDG es de:0.0

Lector: pedalogica 330/1001
El nCDG es de:0.1575706347641941

Lector: abernalz 331/1001
El nCDG es de:0.0

Lector: ticlacpilaser 332/1001
El nCDG es de:0.0

Lector: gracia-1 333/1001
El nCDG es de:0.08422690479595135

Lector: marlluch 334/1001
El nCDG es de:0.024736420541554373

Lector: orlando 335/1001
El nCDG es de:0.23998497166241928

Lector: kannasan 336/1001
El nCDG es de:0.0

Lector: bcalvo-martin-gmail-com 337/1001
El nCDG es de:0.0

Lector: marraco 338/1001
El nCDG es de:0.0

Lector: rosaurba 339/1001
El nCDG es de:0.1387938562963091

Lector: torgo 340/1001
El nCDG es de:0.0

Lector: taniano 341/1001
El nCDG es de:0.0

Lector: segrovich 342/1001
El nCDG es de:0.12240222176822613

Lector: jhsxps 343/1001
El nCDG es de:0.0

Lector: leodeto 344/1001
El nCDG es de:0.031713790369830054

Lector: silke 345/1001
El nCDG es de:0.0

Lector: jorgedeop 346/1001
El nCDG es de:0.07396040275769779

Lector: iler 347/1001
El nCDG es de:0.0

Lector: trivium 348/1001
El nCDG es de:0.0

Lector: pagamue 349/1001
El nCDG es de:0.0

Lector: suso71 350/1001
El nCDG es de:0.092663760407308

Lector: beatryx 351/1001
El nCDG es de:0.0

Lector: atticus 352/1001
El nCDG es de:0.0

Lector: alfmp 353/1001
El nCDG es de:0.0

Lector: jesus-ariza-godina 354/1001
El nCDG es de:0.0

Lector: marijosetdl 355/1001
El nCDG es de:0.15976637502721405

Lector: kr4 356/1001
El nCDG es de:0.04630346245687826

Lector: lolabri 357/1001
El nCDG es de:0.05603473238971033

Lector: daniel-saez 358/1001
El nCDG es de:0.15481352719925381

Lector: galdaf 359/1001
El nCDG es de:0.09393268079765146

Lector: angelapa 360/1001
El nCDG es de:0.02491997095795026

Lector: valganon 361/1001
El nCDG es de:0.04134895061388319

Lector: kampanilla 362/1001
El nCDG es de:0.0

Lector: uttzi 363/1001
El nCDG es de:0.0

Lector: ayna75 364/1001
El nCDG es de:0.0

Lector: 10207357902344974 365/1001
El nCDG es de:0.0

Lector: javier-galdos 366/1001
El nCDG es de:0.09116055878345686

Lector: joanm7 367/1001
El nCDG es de:0.0

Lector: pequi 368/1001

In [25]:
print("Mediana de frecuencia — muestra:", muestra["freq"].median())
print("Mediana de frecuencia — Kaggle:", freq_objetivo.median())

Mediana de frecuencia — muestra: 69.0
Mediana de frecuencia — Kaggle: 72.0

#### 9. Análisis.

In [22]:
#a. Diagnóstico: dónde gana y dónde pierde el modelo.
freq = df_train.groupby("id_lector").size()

res = pd.DataFrame({"id_lector": lectores_test_muestra, "ndcg": ndcg_lista})
res["freq"] = res["id_lector"].map(freq).fillna(0)
res["bucket"] = pd.cut(res["freq"], [-1, 0, 20, 50, 100, 250, np.inf],
                       labels=["cold", "1-20", "21-50", "51-100", "101-250", "250+"])

print(res.groupby("bucket", observed=True)["ndcg"].agg(["mean", "median", "count"]))
print("\nLectores con nDCG = 0:", (res["ndcg"] == 0).mean())

             mean    median  count
bucket
cold     0.000000  0.000000     23
1-20     0.102043  0.041572    281
21-50    0.079955  0.030170    129
51-100   0.070246  0.024944    159
101-250  0.033623  0.000000    236
250+     0.026542  0.000000    173

Lectores con nDCG = 0: 0.5594405594405595

In [23]:
#b. Techo de recall: ¿los 20 libros del GT son siquiera candidatos?
recalls = []
for lid in lectores_test_muestra[:200]:
    cands = set(retrieval(lid))
    gt = set(gt_por_lector[lid].index)
    recalls.append(len(cands & gt) / len(gt))
print("Recall del retrieval:", np.mean(recalls))

Recall del retrieval: 1.0

In [24]:
# Comentario.
#Para un lector fijo, el score de un candidato lo deciden rating_prom_id_lector_autor, 
# n_interacciones_lector_autor y las dos de género. 
# Un lector con 15 libros leyó quizá 12 autores: el modelo tiene que elegir entre "autor que 
# ya leyó" (12 candidatos, señal fuerte) y "autor desconocido" 
# (todo el resto, n=0 y rating=media_global). 
# Es una decisión casi binaria y acierta seguido, porque la gente vuelve a sus autores.

#Un lector con 200 libros leyó 150 autores. Ahora hay 150 candidatos con señal positiva y el modelo
#  tiene que ordenarlos entre sí. 
# Eso ya no lo resuelve n_interacciones_lector_autor, que satura. 
# Y las features que podrían desempatar —calidad del libro, popularidad, novedad— son las tres que
#  tenés comentadas.

#O sea: tus features distinguen bien "conocido vs desconocido" y no distinguen nada dentro de 
# "conocido". El lector pesado vive enteramente dentro de esa segunda categoría.

# Y justamente en el dataset a predecir, la mayoría son personas con muchos libros leídos.
# Osea, los estoy subestimando.